scripts/docker-playground_adapt: Add option to append testcases
Change-Id: I6833f8e6ed71d68231c6d022b40d9940a9efe948

diff --git a/scripts/docker-playground_adapt b/scripts/docker-playground_adapt
--- a/scripts/docker-playground_adapt
+++ b/scripts/docker-playground_adapt
@@ -27,6 +27,7 @@ TESTSUITE_OPT=""
 TESTSUITE=""
 TESTCASES=""
 TEST_SUBDIR=""
+APPEND=""
 
 user_wants() {
 	if [ -n "$NO_PROMPT" ]; then
@@ -65,6 +66,9 @@ while [ "$1" != "" ]; do
 			;;
 		-n | --no-prompt)
 			NO_PROMPT="yes"
+			;;
+		-a|--append)
+			APPEND="yes"
 			;;
 		-b | --branch)
 			BRANCH_OPT="$PARAM"
@@ -226,9 +230,11 @@ if [ -n "$TESTSUITE_OPT" ]; then
 			EXECUTE_LINE="^[ \t]*\[EXECUTE\][ \t\\]*$"
 			NEXT_SECTION_LINE="\[[A-Z_a-z0-9]\+\]"
 			# Delete all lines of the EXECUTE cfg section
-			if ! sed -i '/'"$EXECUTE_LINE"'/,/^'"$NEXT_SECTION_LINE"'/{/^'"$EXECUTE_LINE"'/!{/^'"$NEXT_SECTION_LINE"'/!d}}' $file; then
-				echo "Error removing existing testcases from file $file" >&2
-				REPLACE_ERR=1
+			if [ -z "$APPEND" ]; then
+				if ! sed -i '/'"$EXECUTE_LINE"'/,/^'"$NEXT_SECTION_LINE"'/{/^'"$EXECUTE_LINE"'/!{/^'"$NEXT_SECTION_LINE"'/!d}}' $file; then
+					echo "Error removing existing testcases from file $file" >&2
+					REPLACE_ERR=1
+				fi
 			fi
 			# Append testcase lines
 			for tc in $TESTCASES; do
